### ISSUE TITLE
feedstock-builds on Azure are Broken

### ISSUE THREAD

**Issue by KelSolaar** [conda-forge/colour-science-feedstock#8]
Issue:

@ocefpaf, @conda-forge-admin : I just noticed that the builds are busted on Azure: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=114509&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=c09a5a47-eec3-5700-9284-6f1bd7b23501

Also, and probably related, what is the deal with that directory:

`/home/conda/feedstock_root/build_artifacts/colour-science_1579941129740/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py`

**Comment by ocefpaf** [comment]
> @ocefpaf, @conda-forge-admin 

Please ping `@conda-forge/core` instead of me directly. You'll get help quicker that way. Also, `@conda-forge-admin` is a bot and won't respond.

> Also, and probably related, what is the deal with that directory

Nope. That is a `conda` placeholder directory and it is correct.

I cannot find the PR that updated it to `0.3.15`, did you push directly to `master`? That is a no-no and we may even get a broken package out of it.

Please send a PR next time. I'll see what I can do to fix this.

**Comment by thomasmansencal** [comment]
@ocefpaf : My bad sorry about that! I think I did it for 0.3.14 too.

There are settings in Github to prevent that:

![image](https://user-images.githubusercontent.com/99779/73563058-598cd480-44c1-11ea-8179-01ca01d6b4f1.png)

Not sure how they can be applied globally but it might be worth investigating.

Thanks for the notice about @conda-forge-admin :)
